language: java
jdk: openjdk8

env:
  global:
    - DB_SERVER=localhost
    - DB_DATABASE=durak
    - DB_USER=postgres
    - DB_PASSWORD=

services:
  - postgresql

before_script:
  - psql -c 'create database durak' -U postgres

script: mvn clean test

after_script: ./ci/telegram_notification.sh