version: '2.3'

services:
  sonarqube:
    image: sonarqube
    container_name: durak_sonarqube
    ports:
      - 9001:9000

  prometheus:
    image: prom/prometheus
    container_name: durak_prometheus
    ports:
      - 9090:9090
    volumes:
      - ./metrics/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    container_name: durak_grafana
    ports:
      - 3001:3000
