version: '2.3'

services:
  application:
    container_name: durak_application
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    environment:
      - DB_SERVER=postgres
      - DB_DATABASE=durak
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - REDIS_HOST=redis
    ports:
      - 8081:8080
    healthcheck:
        test: ["CMD-SHELL", "curl -f localhost:8080 || false"]
        interval: 10s
        timeout: 3s
        retries: 3

  postgres:
    image: postgres:11-alpine
    container_name: durak_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=durak
    ports:
      - 5432:5432
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 3s
        retries: 5

  redis:
    image: redis:5-alpine
    container_name: durak_redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli","ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  minio:
    image: minio/minio
    container_name: durak_minio
    environment:
      - MINIO_ACCESS_KEY=durak_access_key
      - MINIO_SECRET_KEY=durak_secret_key
    ports:
      - 9000:9000
    command: server /mnt/minio/data
    healthcheck:
      test: ["CMD-SHELL", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3