version: '2.3'

services:
  sonarqube:
    image: sonarqube
    container_name: durak_sonarqube
    ports:
      - 9001:9000

  prometheus:
    image: prom/prometheus
    container_name: durak_prometheus
    ports:
      - 9090:9090
    volumes:
      - ./metrics/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:6.7.2
    container_name: durak_grafana
    ports:
      - 3001:3000
    volumes:
      - ./metrics/grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./metrics/grafana/dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json
      - ./metrics/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
