spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mvc:
    static-path-pattern: /static/**

  resources:
    cache:
      cachecontrol:
        max-age: 30d
    chain:
      cache: true
      strategy:
        content:
          enabled: true

  datasource:
    url: jdbc:postgresql://${DB_SERVER:localhost}:5432/${DB_DATABASE:durak}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:1234}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: ${DB_MIN_POOL_SIZE:3}
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:2000}
      validation-timeout: ${DB_VALIDATION_TIMEOUT:2000}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

  liquibase:
    change-log: classpath:db/changelog-master.yaml

  redis:
    host: ${REDIS_HOST:localhost}
    jedis:
      pool:
        max-idle: ${REDIS_MAX_IDLE:3}
        max-active: ${REDIS_MAX_TOTAL:10}

  cache:
    redis:
      time-to-live: 5m