global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'durak-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['application:8085']